### PR TITLE
Remove log_errors contextmanager that does nothing

### PR DESCRIPTION
**Pull request by hukkinj1**

### CODE REVIEW

**Comment by hukkinj1** [comment]
@interrogator Is this something you'd be missing if removed? Am I correct that the contextmanager seems to do nothing?

**Comment by interrogator** [comment]
The purpose, probably never properly working, was a context manager that only logs `*Errored` logs.

Its functionality would partially be available by doing `called=None`, `returned=None` on instantiation. but on instantiation is different from context manager use. My question is whether we're better removing this code, or simply making it work, which shouldn't be hard with the current code style. We would just set `self.called/self.returned` to `None` inside this context. Probably at the same time could update the way the other context managers work to work that way too.

Any final thoughts? I understand we're probably just removing dead code, but maybe we should actually be making it work. Not sure, rarely used the context managers anyway.

**Comment by hukkinj1** [comment]
Yeah, we don't use this contextmanager, so at least I have zero interest in fixing this, and would prefer removing it if its not used, not properly tested, etc. But if you want to fix it, test it, so that it does what it's supposed to I'm not against it. Otherwise I think we just merge this.

**Comment by interrogator** [comment]
Nah, I don't want to fix it now, I think i'm fine to delete and then write it up again properly if anybody ever needs it. with that `contextmanager` decorator, it's all of 10 lines of code to make it work properly. @gcarq can merge

**Pull request merged**
