### PR TITLE
Cleaning some Bitpanda specific alert logic

### PR DESCRIPTION
**Pull request by hukkinj1**

### CODE REVIEW

**Comment by interrogator** [comment]
great, totally approve of removing the old alert level logic. good to see jon's got you doing the important stuff, too.

**Comment by interrogator** [comment]
@hukkinj1 weird looking CI fail, but I can't see a rerun pipeline. If you also don't have a button, can you just do a dummy commit on this branch? In fact do the `class Loggo:` change :wink:

**Comment by hukkinj1** [comment]
The pipeline is not failing here, but Travis did some change so GitHub doesnt know what happened in the pipeline.

**Comment by interrogator** [comment]
OK you guys will figure it out? It isn't just exit code thing? Just 'mock' the exit code for now if we want

**Pull request merged**
