### PR TITLE
Try out and enforce `black` for all code formatting

### PR DESCRIPTION
**Pull request by hukkinj1**
I don't expect this to be merged (although would love it if it happened), but using this MR to start a discussion, and showcase how well black would do at code formatting for us. The benefits of using something like this are pretty clear, read e.g. the first introduction paragraph here: https://pypi.org/project/black/ .

Black has been gaining a lot of traction in the Python community. It's already enforced in py-test codebase, will be in Django codebase (https://twitter.com/andrewgodwin/status/1127027840296177666) and even the Python stdlib (!!!) (https://twitter.com/llanga/status/1123980467911495680). Black was moved under the Python Software Foundation (https://www.python.org/psf/) umbrella last month.

Loggo code is already decently formatted, so the formatting changes in this MR are fairly minor. Here's an example of what magic black can do to absolutely garbage code: https://black.now.sh .

I think we should very seriously consider using black, and from my own side am already willing to vote "yes".

### CODE REVIEW

**Comment by gcarq** [comment]
The resulting code looks very clean and having one format everyone is familiar with makes a lot of sense. ACK from my side.

**Comment by interrogator** [comment]
I mostly like it, the only issues are that I prefer single quotation marks, and also:

```python
def function(arg,
             arg2):
```

to

```python
def function(arg,
    arg2):
```
But yeah, enforcing a style and having a tool that autoformats it seems like a good idea.

How do you guys feel about `black --skip-string-normalization --check` ?

**Comment by hukkinj1** [comment]
Thanks for the input.

I would prefer no configuration whatsoever, as that's in part the whole point: never ever again having to have the discussion on which quotation mark or indentation style someone likes the most :)

Also when it comes to quotation marks, I think `black` documentation makes stronger arguments than "I prefer" for the double quotes. Plus the fact that we so often use the single quote character `'` in strings. With double quotes, we don't need to escape that character.

**Comment by interrogator** [comment]
Yep, for the record, though I like my style, I think it's better to use black defaults overall.

**Pull request merged**
